### ISSUE TITLE
How can I import the issues to my repo? I am having a hard time transfering them to my github. #bug 

### ISSUE THREAD

**Issue by EnkrateiaLucca** [oleksis/machine-learning-articles#89]
## Key Takeaways
* 
* 

## Useful Code Snippets
```python
#Add your codes here
import numpy as np
import pandas as pd

```

## Useful Tools
* 
*

**Comment by oleksis** [comment]
You need follow some steps before import the Issues to your repo, like first enable the Issues in your [Repo -> Settings](https://github.com/oleksis/machine-learning-articles#how-to-contribute) 

The last step I add  the workflow that you can trigger manually from the Actions tab.

Let me know if you make it work!

**Comment by EnkrateiaLucca** [comment]
Thanks man. I did enable but for some reason it kept not showing the the papers.

Thanks for answering!
Cheers!

________________________________
De: Oleksis Fraga Menéndez <notifications@github.com>
Enviado: quarta-feira, 23 de setembro de 2020 20:50
Para: oleksis/machine-learning-articles <machine-learning-articles@noreply.github.com>
Cc: LUCAS SOARES <lucasbnsoares@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [oleksis/machine-learning-articles] How can I import the issues to my repo? I am having a hard time transfering them to my github. #bug (#89)


You need follow some steps before import the Issues to your repo, like first enable the Issues in your Repo -> Settings<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foleksis%2Fmachine-learning-articles%23how-to-contribute&data=02%7C01%7C%7C92957624147243491cd708d86002461c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637364910161191834&sdata=DyixPrwz00F9GBkO2BONrOfgSiYBK%2B0uhgQQ0GDulF0%3D&reserved=0>

Let me know if you make it work!

**Comment by oleksis** [comment]
> Thanks man. I did enable but for some reason it kept not showing the the papers. 

- One reason can be your fork is one **Template** try set like normal (fork) repository. 

- Then set your Personal Access Token: [secrets.ACTIONS_SECRET](https://github.com/oleksis/machine-learning-articles/blob/fe5bb828add68192bb9258cc063f958deec3f237/.github/workflows/ciff.yml#L40) for the GitHub Action can use when you run the workflow.

- In your Actions tab in the repository you can find the workflow **Create Issues** and triggered manually when you selecting the workflow 

Cheers!

**Comment by EnkrateiaLucca** [comment]
Thanks Oleksis very much for the help I’ll try it out

cheers

Sent from my iPad

On 23 Sep 2020, at 22:46, Oleksis Fraga Menéndez <notifications@github.com> wrote:

﻿

Thanks man. I did enable but for some reason it kept not showing the the papers.

  *   One reason can be your fork is one Template try set like normal (fork) repository.

  *   Then set your Personal Access Token: secrets.ACTIONS_SECRET<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foleksis%2Fmachine-learning-articles%2Fblob%2Ffe5bb828add68192bb9258cc063f958deec3f237%2F.github%2Fworkflows%2Fciff.yml%23L40&data=02%7C01%7C%7Cd91d52c0c0a5459cdac008d8600a21c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637364943911631568&sdata=Uw9g3KmVYkYKKmZBZE%2F9JuavPW4VJfpqUu2rCUOCCw4%3D&reserved=0> for the GitHub Action can use when you run the workflow.

  *   In your Actions tab in the repositoryb you can find the workflow Create Issues and triggered manually when you selecting the workflow

Cheers!
